import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import SessionProvider from "@/providers/session-provider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/consts";
import ClientProvider from "@/providers/apollo-provider";
import MuiProvider from "@/providers/mui-provider";
import "./globals.css";
import StoreProvider from "@/providers/store-provider";
import { Toaster } from "@/components/ui/toaster";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const bahnschrift = localFont({
  src: "./fonts/bahnschrift.ttf",
  variable: "--font-bahnschrift",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const messages = await getMessages();
  const locale = await getLocale();
  console.log("Locale:", locale);
  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bahnschrift.variable} antialiased bg-background text-foreground`}
      >
        <ClientProvider>
          <StoreProvider>
            <SessionProvider session={session}>
              <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
              >
                <MuiProvider>
                  <NextIntlClientProvider messages={messages}>
                    {children}
                    <Toaster />
                  </NextIntlClientProvider>
                </MuiProvider>
              </ThemeProvider>
            </SessionProvider>
          </StoreProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
